#' @include error_checking.R

# Begin Plot Summary IV
#' Plot Information Value Summary
#'
#' It gives the user the ability to plot the Information Value by characteristic.
#' The chart only shows characteristics with a valid IV.
#' Example shown on \code{smbinning.sumiv} section.
#' @param sumivt A data frame saved after \code{smbinning.sumiv}.
#' @param cex Optional parameter for the user to control the font size of the characteristics
#' displayed on the chart. The default value is 0.9
#' @return The command \code{smbinning.sumiv.plot} returns a plot that shows the IV
#' for each numeric and factor characteristic in the dataset.
#' @export
smbinning.sumiv.plot <- function(sumivt, cex = 0.9) {
  # Check sumivt is a dataframe
  tryCatch({
    assertthat::assert_that(is.data.frame(sumivt))
  },
  error = function(e) {
    message("Data sumivt not a dataframe.")
    return(NA)
  })

  if (names(sumivt[1]) != "Char" |
      names(sumivt[2]) != "IV") {
    return("Not from smbinning.sumiv")
  }
  sumivtplot <- sumivt
  sumivtplot <- sumivtplot[complete.cases(sumivtplot$IV), ]
  sumivtplot <- sumivtplot[order(sumivtplot$IV), ]
  sumivtplot <- cbind(sumivtplot, Desc = ifelse(
    sumivtplot$IV >= 0.3,
    "1:Strong",
    ifelse(sumivtplot$IV >= 0.1, "2:Medium", "3:Weak")
  ))
  unique(sumivtplot$Desc)
  sumivtplot$Desc <- as.factor(sumivtplot$Desc)
  smbsumivplot <- dotchart(
    sumivtplot$IV,
    main = "Information Value",
    labels = sumivtplot$Char,
    pch = ifelse(sumivtplot$IV >= 0.3, 21, ifelse(sumivtplot$IV >=
                                                    0.1, 21, 1)),
    color = ifelse(
      sumivtplot$IV >= 0.3,
      "black",
      ifelse(sumivtplot$IV >= 0.1, "black", "black")
    ),
    bg = ifelse(
      sumivtplot$IV >= 0.3,
      "black",
      ifelse(sumivtplot$IV >= 0.1, "gray75", "white")
    ),
    groups = sumivtplot$Desc,
    cex = cex
  )
}
# End Plot Summary IV




# Begin Plotting
#' Plots after binning
#'
#' It generates plots for distribution, bad rate, and weight of evidence after running \code{smbinning}
#' and saving its output.
#' @param ivout An object generated by binning.
#' @param option Distribution ("dist"), Good Rate ("goodrate"), Bad Rate ("badrate"), and Weight of Evidence ("WoE").
#' @param sub Subtitle for the chart (optional).
#' @examples
#' # Load library and its dataset
#' library(smbinning)
#'
#' # Example 1: Numeric variable (1 page, 4 plots)
#' result=smbinning(df=smbsimdf1,y="fgood",x="cbs1") # Run and save result
#' par(mfrow=c(2,2))
#' boxplot(smbsimdf1$cbs1~smbsimdf1$fgood,
#'         horizontal=TRUE, frame=FALSE, col="lightgray",main="Distribution")
#' mtext("Credit Score",3)
#' smbinning.plot(result,option="dist",sub="Credit Score")
#' smbinning.plot(result,option="badrate",sub="Credit Score")
#' smbinning.plot(result,option="WoE",sub="Credit Score")
#' par(mfrow=c(1,1))
#'
#' # Example 2: Factor variable (1 plot per page)
#' result=smbinning.factor(df=smbsimdf1,y="fgood",x="inc",maxcat=11)
#' smbinning.plot(result,option="dist",sub="Income Level")
#' smbinning.plot(result,option="badrate",sub="Income Level")
#' smbinning.plot(result,option="WoE",sub="Income Level")
#' @export
smbinning.plot <- function(ivout, option = "dist", sub = "") {
  r <- ifelse(ivout$ivtable[nrow(ivout$ivtable) - 1, 2] == 0, 2, 1)

  if (option == "dist") {
    # Distribution
    x_upper <- nrow(ivout$ivtable) - r
    y_upper <- max(ivout$ivtable[1:x_upper, 8]) * 1.25
    ch_dist <- barplot(
      ivout$ivtable[1:x_upper, 8],
      names.arg = ivout$ivtable[1:x_upper, 1],
      axes = F,
      main = "Percentage of Cases",
      ylim = c(0, y_upper),
      col = gray.colors(length(unique(ivout$ivtable[1:x_upper, 1])))
    )
    text(
      x = ch_dist,
      y = ivout$ivtable[1:x_upper, 8],
      label = round(ivout$ivtable[1:x_upper, 8] * 100, 1),
      pos = 3,
      cex = 1
    )
    abline(h = 0)
    mtext(sub, 3)
  } else if (option == "goodrate") {
    # Good Rate
    x_upper <- nrow(ivout$ivtable) - r
    y_upper <- max(ivout$ivtable[1:x_upper, 9], na.rm = TRUE) * 1.25
    ch_goodrate <- barplot(
      ivout$ivtable[1:x_upper, 9],
      names.arg = ivout$ivtable[1:x_upper, 1],
      axes = F,
      main = "Good Rate (%)",
      ylim = c(0, y_upper),
      col = gray.colors(length(unique(ivout$ivtable[1:x_upper, 1])))
    )
    text(
      x = ch_goodrate,
      y = ivout$ivtable[1:x_upper, 9],
      label = round(ivout$ivtable[1:x_upper, 9] * 100, 1),
      pos = 3,
      cex = 1
    )
    abline(h = 0)
    mtext(sub, 3)
  } else if (option == "badrate") {
    # Bad Rate
    x_upper <- nrow(ivout$ivtable) - r
    y_upper <-
      max(ivout$ivtable[1:x_upper, 10], na.rm = TRUE) * 1.25
    ch_badrate <- barplot(
      ivout$ivtable[1:x_upper, 10],
      names.arg = ivout$ivtable[1:x_upper, 1],
      axes = F,
      main = "Bad Rate (%)",
      ylim = c(0, y_upper),
      col = gray.colors(length(unique(ivout$ivtable[1:x_upper, 1])))
    )
    text(
      x = ch_badrate,
      y = ivout$ivtable[1:x_upper, 10],
      label = round(ivout$ivtable[1:x_upper, 10] * 100, 1),
      pos = 3,
      cex = 1
    )
    abline(h = 0)
    mtext(sub, 3)
  } else if (option == "WoE") {
    # WoE
    x_upper <- nrow(ivout$ivtable) - r
    y_upper <-
      max(ivout$ivtable[1:x_upper, 13], na.rm = TRUE) * 1.25
    y_lower <-
      min(ivout$ivtable[1:x_upper, 13], na.rm = TRUE) * 1.25
    ch_woe <- barplot(
      ivout$ivtable[1:x_upper, 13],
      names.arg = ivout$ivtable[1:x_upper, 1],
      axes = F,
      main = "Weight of Evidence",
      ylim = c(y_lower, y_upper),
      col = gray.colors(length(unique(ivout$ivtable[1:x_upper, 1])))
    )
    text(
      x = ch_woe,
      y = ivout$ivtable[1:x_upper, 13],
      label = round(ivout$ivtable[1:x_upper, 13], 2),
      pos = 3,
      cex = 1
    )
    abline(h = 0)
    mtext(sub, 3)
  } else {
    return("Options are dist, goodrate, badrate, or WoE")
  }
}
# End Plotting



# Ini: Metrics Plot
#' Visualization of a Classification Matrix
#'
#' It generates four plots after running and saving the output report from \code{smbinning.metrics}.
#' @param df Data frame generated with \code{smbinning.metrics}.
#' @param cutoff Value of the classifier that splits the data between positive (>=) and negative (<).
#' @param plot Plot to be drawn. Options are: 'cmactual' (default),'cmactualrates','cmmodel','cmmodelrates'.
#' @examples
#' # Load library and its dataset
#' library(smbinning)
#' smbmetricsdf=smbinning.metrics(dataset=smbsimdf1, prediction="cbs1",
#'                                actualclass="fgood", returndf=1)
#'
#' # Example 1: Plots based on optimal cutoff
#' smbinning.metrics.plot(df=smbmetricsdf,plot='cmactual')
#'
#' # Example 2: Plots using user defined cutoff
#' smbinning.metrics.plot(df=smbmetricsdf,cutoff=600,plot='cmactual')
#' smbinning.metrics.plot(df=smbmetricsdf,cutoff=600,plot='cmactualrates')
#' smbinning.metrics.plot(df=smbmetricsdf,cutoff=600,plot='cmmodel')
#' smbinning.metrics.plot(df=smbmetricsdf,cutoff=600,plot='cmmodelrates')
#' @export
smbinning.metrics.plot <-
  function(df, cutoff = NA, plot = "cmactual") {
    if (names(df)[1] != "Prediction" | names(df)[2] != "CntGood") {
      return("Data not from smbinning.metrics.")

    } else if (!is.na(cutoff) & !is.numeric(cutoff)) {
      # Check if target variable is numeric
      return("'cutoff' must be numeric.")

    } else if (!is.na(cutoff) &
               (max(df$Prediction) < cutoff |
                min(df$Prediction) > cutoff)) {
      # Check if target variable is numeric
      return("'cutoff' out of range.")

    } else if (plot != "cmactual" &
               plot != "cmactualrates" & plot != "cmmodel" &
               plot != "cmmodelrates") {
      return("'plot' options are: 'auc', 'ks' or 'none'.")

    } else {
      df$YoudenJ <- df$Sensitivity + df$Specificity - 1
      optcut <- df[df$YoudenJ == max(df$YoudenJ),]$Prediction
      df$YoudenJ <- NULL

      # If cutoff is specified
      if (!is.na(cutoff)) {
        if ((cutoff %in% df$Prediction) == FALSE) {
          optcut <- df[which.min(abs(as.numeric(df$Prediction) - cutoff)), 1]
        } else {
          optcut <- cutoff
        }
      }


      # Confusion Matrix Components
      tp <- df[df$Prediction == optcut,]$CumDescGood
      fp <- df[df$Prediction == optcut,]$CumDescBad
      fn <- df[df$Prediction == optcut,]$FN
      tn <- df[df$Prediction == optcut,]$TN

      p <- sum(df$CntGood)
      n <- sum(df$CntBad)

      # CM Metrics
      accuracy <- (tp + tn) / (tp + fp + tn + fn)
      sensitivity <- tp / p
      FNR <- fn / p
      specificity <- tn / n
      FPR <- fp / n
      precision <- tp / (tp + fp)
      invprecision <- tn / (fn + tn)
      FDR <- fp / (tp + fp)
      FOR <- fn / (fn + tn)
      # For AUC Calculation (Trapezoid Method)
      df$TPR <- df$Sensitivity
      df$FPR <- 1 - df$Specificity
      df$MgAUC <- 0
      a <- which(names(df) == "MgAUC")
      f <- which(names(df) == "FPR")
      t <- which(names(df) == "TPR")
      for (i in 1:nrow(df) - 1) {
        df[i, a] <-
          0.5 * (df[i, t] + df[i + 1, t]) * (df[i, f] - df[i + 1, f])
      }
      # AUC
      auc <- sum(df$MgAUC)
      df$TPR <- NULL
      df$FPR <- NULL
      df$MgAUC <- NULL

      # KS
      df$MgKS <- abs(df$PctCumAscGood - df$PctCumAscBad)
      ks <- as.numeric(max(df$MgKS))
      df$MgKS <- NULL

      # Classification Matrix
      cmnbr <- matrix(c(tp, fn, fp, tn), nrow = 2, ncol = 2)
      cmpctactual <- matrix(c(sensitivity, FNR, FPR, specificity),
                            nrow = 2,
                            ncol = 2)
      cmpctmodel <- matrix(c(precision, FDR, FOR, invprecision),
                           nrow = 2,
                           ncol = 2)

      # CM, where X-axis is actual class
      if (plot == "cmactual") {
        cmnbrplot <- cmnbr
        colnames(cmnbrplot) <-
          c("Actual+\n[ TP | FN ]", "Actual-\n[ FP | TN ]") # Actuals
        rownames(cmnbrplot) <- c("Model+", "Model-") # Model
        bpactual =
          barplot(
            cmnbrplot,
            ylim = c(0, round(1.25 * max(cmnbrplot), 0)),
            col = c("grey50", "grey85"),
            beside = TRUE,
            axes = TRUE,
            border = NA,
            legend.text = TRUE,
            args.legend = list(
              x = "top",
              border = NA,
              bty = "n",
              horiz = F
            )
          )
        mtext(
          side = 3,
          "Classification Matrix",
          line = 2,
          cex = 1.2,
          font = 2
        )
        mtext(
          side = 3,
          paste0("Records by Actual Class. Cutoff >=", optcut),
          line = 0.75,
          cex = 1
        )
        mtext(
          side = 1,
          "Actual Class",
          line = 3,
          cex = 1,
          font = 2
        )
        abline(h = 0) # Horizontal line
        text(
          x = bpactual,
          y = cmnbrplot,
          label = cmnbrplot,
          pos = 3,
          cex = 1
        )
      }


      # CM Percentages, where X-axis is actual class
      if (plot == "cmactualrates") {
        cmpctactualplot <- cmpctactual
        colnames(cmpctactualplot) <-
          c("Actual+\n[ Sensitivity | FNR ]",
            "Actual-\n[ FPR | Specificity ]") # Actuals
        rownames(cmpctactualplot) <- c("Model+", "Model-") # Model
        bpactualpct =
          barplot(
            cmpctactualplot,
            ylim = c(0, 1),
            col = c("grey50", "grey85"),
            beside = TRUE,
            axes = TRUE,
            border = NA,
            legend.text = TRUE,
            args.legend = list(
              x = "top",
              border = NA,
              bty = "n",
              horiz = F
            )
          )
        mtext(
          side = 3,
          "Classification Matrix",
          line = 2,
          cex = 1.2,
          font = 2
        )
        mtext(
          side = 3,
          paste0("Percentage by Actual Class. Cutoff >=", optcut),
          line = 0.75,
          cex = 1
        )
        mtext(
          side = 1,
          "Actual Class",
          line = 3,
          cex = 1,
          font = 2
        )
        abline(h = 0) # Horizontal line
        text(
          x = bpactualpct,
          y = cmpctactualplot,
          label = round(cmpctactualplot, 4),
          pos = 3,
          cex = 1
        )
      }

      # CM Numbers, where X-axis is model prediction
      if (plot == "cmmodel") {
        cmnbrplot <- cmnbr
        colnames(cmnbrplot) <- c("Actual+", "Actual-") # Actuals
        rownames(cmnbrplot) <-
          c("Model+\n[ TP | FP ]", "Model-\n [ FN | TN ]") # Model
        bpmodel =
          barplot(
            t(cmnbrplot),
            ylim = c(0, round(1.25 * max(cmnbrplot), 0)),
            col = c("grey50", "grey85"),
            beside = TRUE,
            axes = TRUE,
            border = NA,
            legend.text = TRUE,
            args.legend = list(
              x = "top",
              border = NA,
              bty = "n",
              horiz = F
            )
          )
        mtext(
          side = 3,
          "Classification Matrix",
          line = 2,
          cex = 1.2,
          font = 2
        )
        mtext(
          side = 3,
          paste0("Records by Model Prediction. Cutoff >=", optcut),
          line = 0.75,
          cex = 1
        )
        mtext(
          side = 1,
          "Model Prediction",
          line = 3,
          cex = 1,
          font = 2
        )
        abline(h = 0) # Horizontal line
        text(
          x = bpmodel,
          y = t(cmnbrplot),
          label = t(cmnbrplot),
          pos = 3,
          cex = 1
        )
      }

      # CM Numbers, where X-axis is model prediction
      if (plot == "cmmodelrates") {
        cmpctmodelplot <- cmpctmodel
        colnames(cmpctmodelplot) <-
          c("Model+\n[ PPV | FDR ]", "Model-\n[ FOR | NPV ]") # Actuals
        rownames(cmpctmodelplot) <- c("Actual+", "Actual-") # Model
        bpactualpct =
          barplot(
            cmpctmodelplot,
            ylim = c(0, 1),
            col = c("grey50", "grey85"),
            beside = TRUE,
            axes = TRUE,
            border = NA,
            legend.text = TRUE,
            args.legend = list(
              x = "top",
              border = NA,
              bty = "n",
              horiz = F
            )
          )
        mtext(
          side = 3,
          "Classification Matrix",
          line = 2,
          cex = 1.2,
          font = 2
        )
        mtext(
          side = 3,
          paste0("Percentage by Model Prediction. Cutoff >=", optcut),
          line = 0.75,
          cex = 1
        )
        mtext(
          side = 1,
          "Model Prediction",
          line = 3,
          cex = 1,
          font = 2
        )
        abline(h = 0) # Horizontal line
        text(
          x = bpactualpct,
          y = cmpctmodelplot,
          label = round(cmpctmodelplot, 4),
          pos = 3,
          cex = 1
        )
      }

    } # end else
  }

# End: Metrics Plot

