#' @include error_checking.R

#' Generation of SQL Code After Scaled Model
#'
#' After applying \code{smbinning.scaling} to the model, \code{smbinning.scoring.sql} generates a SQL code
#' that creates and updates all variables present in the scaled model. Example shown on \code{smbinning.scaling} section.
#' @param smbscaled Object generated using \code{smbinning.scaling}.
#' @return The command \code{smbinning.scoring.sql} generates a SQL code to implement the model the model in SQL.
#' @export
smbinning.scoring.sql <- function(smbscaled) {
  if (missing(smbscaled)) {
    return(stop("Argument 'smbscaled' is missing"))

  } else if (names(smbscaled)[1] != "logitscaled") {
    return(stop("'smbscaled' must come from 'smbinning.scaling'"))

  } else {
    logitscaled <- smbscaled$logitscaled
    # SQL code 1: Create table
    logitscaleddf <- data.frame(logitscaled)
    logitscaleddf <- logitscaleddf[-1, ] # Remove (intercept)
    uniquechctrs <-
      unique(logitscaleddf$Characteristic) # Characteristics
    codecreate <- list()
    codecreate <- c(codecreate,
      paste("-- Replace 'TableName' with your table in SQL \n"))
    codecreate <-
      c(codecreate, "alter table TableName add \n") # First line of the sql code
    for (i in seq_len(uniquechctrs)) {
      pointname <- paste(uniquechctrs[[i]], "Points", sep = "")
      codecreate <-
        c(codecreate, paste(pointname, "int not null, \n", sep =
          " "))
    }
    codecreate <-
      c(codecreate, paste("Score", "int not null \n", sep = " "))
    codecreate <- c(codecreate, paste("go \n", sep = " "))

    sqlcreate <- character()
    for (i in seq_len(codecreate)) {
      sqlcreate <- paste(sqlcreate, codecreate[[i]], sep = "")
    }

    # SQL code 2: Update table
    codeupdate <- list()
    codeupdate <- c(codeupdate,
      paste("\n-- Replace 'TableName' with your table in SQL \n"))
    codeupdate <- c(codeupdate, paste("update TableName set \n"))
    for (i in seq_len(uniquechctrs)) {
      subdf <- subset(logitscaleddf,
        logitscaleddf$Characteristic == uniquechctrs[i])
      pointname <- paste(uniquechctrs[[i]], "Points", sep = "")
      codeupdate <- c(codeupdate, pointname, "=", "( \n", sep = " ")
      codeupdate <- c(codeupdate, "case \n")
      for (j in 1:dim(subdf)[1]) {
        codeupdate <- c(codeupdate,
          paste(
            " when",
            subdf[["Characteristic"]][j],
            paste("= ", "'", gsub("'", "''", subdf[["Attribute"]][j]), "'", sep =
              ""),
            "then",
            subdf[["Points"]][j],
            " \n",
            sep = " "
        ))
      }
      codeupdate <- c(codeupdate, " else Null end \n ), \n")
    }
    codeupdate <- c(codeupdate, "Score=( \n")
    for (i in seq_len(uniquechctrs)) {
      pointname <- paste(uniquechctrs[[i]], "Points", sep = "")
      if (i == 1) {
        codeupdate <- c(codeupdate, paste(" ", pointname, sep = " "))
      } else {
        codeupdate <- c(codeupdate, paste(" +", pointname, sep = " "))
      }
    }
    codeupdate <- c(codeupdate, "\n) \n")

    sqlupdate <- character()
    for (i in seq_len(codeupdate)) {
      sqlupdate <- paste(sqlupdate, codeupdate[[i]], sep = "")
    }
  }
  return(cat(sqlcreate, sqlupdate))
}



#' SQL Code
#'
#' Outputs a SQL code to facilitate the generation of new binned characteristics
#' in a SQL environment. User must define table and new characteristic name.
#' @param ivout An object generated by \code{smbinning}.
#' @return A text with the SQL code for binning.
#' @examples
#' # Load library and its dataset
#' library(smbinning)
#'
#' # Example 1: Binning a numeric variable
#' result <- smbinning(df = smbsimdf1, y = "fgood", x = "cbs1") # Run and save result
#' smbinning.sql(result)
#'
#' # Example 2: Binning for a factor variable
#' result <- smbinning.factor(df = smbsimdf1, x = "inc", y = "fgood", maxcat = 11)
#' smbinning.sql(result)
#'
#' # Example 3: Customized binning for a factor variable
#' result <- smbinning.factor.custom(
#'   df = smbsimdf1, x = "inc", y = "fgood",
#'   c("'W01','W02'", "'W03','W04','W05'",
#'     "'W06','W07'", "'W08','W09','W10'"))
#' smbinning.sql(result)
#'
#' @export
smbinning.sql <- function(ivout) {
  if (is.null(ivout$groups)) {
    lines <- nrow(ivout$ivtable) - 2
    sqlcodetable <- as.list(matrix(ncol = 0, nrow = 0))
    sqlcodetable <- rbind(
      " alter table  'TableName'  add  'NewCharName'\n go\n update  'TableName'  set  'NewCharName'\n case\n"
    )
    for (k in 1:lines) {
      sqlcodetable <- rbind(
        sqlcodetable,
        paste(
          "when",
          ivout$x,
          ivout$ivtable[k, 1],
          "then",
          "'",
          sprintf("%02d", k),
          ":",
          ivout$x,
          gsub("'", "", ivout$ivtable[k, 1]),
          "'\n"
        )
      )
    }
    k <- nrow(ivout$ivtable) - 1
    sqlcodetable <- rbind(
      sqlcodetable,
      paste(
        "when",
        ivout$x,
        "Is Null then",
        "'",
        sprintf("%02d", k),
        ":",
        ivout$x,
        "Is Null' \n"
      )
    )
    sqlcodetable <-
      rbind(sqlcodetable, paste("else '99: Error' end"))
    sqlcodetable
    # Some Make Up
    sqlcodetable <- gsub(" '", "'", sqlcodetable)
    sqlcodetable <- gsub("' ", "'", sqlcodetable)
    sqlcodetable <- gsub("then", "then ", sqlcodetable)
    sqlcodetable <- gsub("'then", "' then ", sqlcodetable)
    sqlcodetable <- gsub("then  ", "then ", sqlcodetable)
    sqlcodetable <- gsub("else", "else ", sqlcodetable)
    sqlcodetable <- gsub("'end", "' end ", sqlcodetable)
    sqlcodetable <- gsub(" :", ":", sqlcodetable)
    sqlcodetable <- gsub("='", "= '", sqlcodetable)
    return(cat(gsub(",", "", toString(sqlcodetable))))
    # For customized factor 20170910
  } else {
    sqlcodetable <- as.list(matrix(ncol = 0, nrow = 0))
    sqlcodetable <- rbind(
      " alter table  'TableName'  add  'NewCharName'\n go\n update  'TableName'  set  'NewCharName'\n case\n"
    )
    for (i in seq_len(ivout$groups)) {
      sqlcodetable <- rbind(
        sqlcodetable,
        paste(
          " when",
          ivout$x,
          "in (",
          ivout$groups[i],
          ") then",
          "'",
          sprintf("%02d", i),
          ":",
          ivout$x,
          gsub("'", "", ivout$groups[i]),
          "'\n"
        )
      )
    }
    i <- length(ivout$groups) + 1
    sqlcodetable <- rbind(
      sqlcodetable,
      paste(
        " when",
        ivout$x,
        "Is Null then",
        "'",
        sprintf("%02d", i),
        ":",
        ivout$x,
        "Is Null'\n"
      )
    )
    sqlcodetable <-
      rbind(sqlcodetable, paste(" else '99: Error' end"))
    # Some Make Up
    sqlcodetable <- gsub(" '", "'", sqlcodetable)
    sqlcodetable <- gsub("' ", "'", sqlcodetable)
    sqlcodetable <- gsub("then", "then ", sqlcodetable)
    sqlcodetable <- gsub("'then", "' then ", sqlcodetable)
    sqlcodetable <- gsub("then  ", "then ", sqlcodetable)
    sqlcodetable <- gsub("else", "else ", sqlcodetable)
    sqlcodetable <- gsub("'end", "' end ", sqlcodetable)
    sqlcodetable <- gsub(" :", ":", sqlcodetable)
    sqlcodetable <- gsub("='", "= '", sqlcodetable)
    return(cat(gsub(", ", "", toString(sqlcodetable))))
  }
}



